### ISSUE TITLE
Race condition in Executor.ncores?

### ISSUE THREAD

**Issue by seibert** [mrocklin/distributed#13]
In an IPython notebook, if I execute the following two lines in a cell:
```
client = distributed.Executor('192.168.5.1:8787')
client.ncores
```
I get an exception:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-d814f40dfc7a> in <module>()
      1 #local_client = Client(sched.address_to_clients)
      2 client = distributed.Executor('192.168.5.1:8787')
----> 3 client.ncores

AttributeError: 'Executor' object has no attribute 'ncores'
```
But if I split those statements into two cells and run them manually (with a human-scale delay between the two statements), `client.ncores` works fine.

**Comment by mrocklin** [comment]
Yeah, there is a race condition here.  `Executor.ncores` should be considered read-only and mostly for debugging purposes.

What's going on here is that most of the gritty logic is happening in the *scheduler*, which runs in a separate thread.  The scheduler is the beating heart of executor; the executor is mostly UI code on top of the scheduler.  The scheduler runs in a single thread, uses coroutines for concurrency, and so avoids locks.

For debugging purposes however it ends up being very handy to have access to a lot of the internal state of the scheduler so we tack it on to the executor, completely unsafely.

For this particular issue we should probably tack on `ncores` at object initialization and fill it in later once it gets occupied.

**Comment by mrocklin** [comment]
Fixed by https://github.com/mrocklin/distributed/commit/64f25ac26ffc344486459c06b5c1eab63e6d5da8

**Comment by seibert** [comment]
Ah, this would also explain how I would sometimes see what appeared to be stale information in `ncores` and `futures` if the scheduler had not yet updated things.

**Comment by mrocklin** [comment]
To be clear, information should be updated within a millisecond or two.

I run into this issue personally when I try to pprint out the full dask dependency graph.  If we want to keep some of these long term then we'll probably have to rely on the GIL and do `.copy` operations.

**Comment by mrocklin** [comment]
Executor(...) will now block until after it has synchronized with the center.
