### ISSUE TITLE
Dask.array + distributed notes

### ISSUE THREAD

**Issue by mrocklin** [mrocklin/distributed#14]
### Setup

I'm playing with `dask.array` on a `distributed` cluster.  I've scattered some ECMWF data onto four `m3.2xlarge`s.  Data is sitting as numpy arrays in memory.

```python
In [22]: x
Out[22]: dask.array<x, shape=(236, 721, 1440), dtype=float64, chunksize=(4, 721, 1440)>
```

### Times

*  Getting a single element from the array, `x[0, 0, 0]` -- 8ms.  Hooray for low overhead
*  Pulling out a single time slice (720 / 1440 float64s) `x[100]` -- 130 ms 
*  Computing the mean along the non-chunked axes (`x.mean(axis=[1, 2])`) -- 300ms
*  Computing the mean along the chunked axis (`x.mean(axis=0)`) -- 14s. 
     This is unfortunate.  This is probably the result of moving around 400MB between workers on a not-super-fast interconnect.  This would be faster if we did a reduction tree, rather than all-to-one.
*  Computing `(x - x.mean()).sum()` is taking a long long time.  This is likely because in some cases it's moving the blocks of `x` to the `x.mean()` value, rather than the other way around.

Regarding the last point,  imagine that the intermediate result storing the mean of the array is on Alice while a particular chunk, `(x, 0, 0)` is on Bob.  We want to copy the mean from Alice to Bob (this is cheap) and not the chunk from Bob to Alice (this is expensive.)  If we know how large each intermediate result is then the solution is obvious.  Unfortunately we don't currently know how large each value is and so it's hard to make this determination.

### Tracking data size

*  Dynamically: `distributed` workers can run some `nbytes` function on results and send that information back to the scheduler when they report work-finished.
*  Statically: `dask.array` can figure out the size of every chunk robustly.  This would require us to tack on more metadata onto dask collections generally and pass it through as they create new collections

I'm currently leaning towards the first solution, putting the weight of this on `distributed`, but the second solution does open up some other possibilities with dask.

cc @shoyer @freeman-lab

**Comment by mrocklin** [comment]
https://gist.github.com/a6f4074e7537eabb776f

**Comment by jcrist** [comment]
If we attached the size metadata to the graph, we'd probably want to do so in a consistent way across all collections/non-collections. One potential solution would be to use a namedtuple: `namedtuple('weightedtuple', ('key', 'size'))`, where `key` is what is normally the key. This would allow it to work for dataframe, array, or user implemented things transparently. It does complicate the graphs though, so doing this in the scheduler (if possible) would be a lot nicer.

**Comment by mrocklin** [comment]
Tiny blog about all of this http://blaze.pydata.org/blog/2015/11/13/distributed-array/
