### ISSUE TITLE
No `daemon` argument to `threading.Thread` in Python 2.7

### ISSUE THREAD

**Issue by seibert** [mrocklin/distributed#18]
This line raises an exception in Python 2.7:
https://github.com/mrocklin/distributed/blob/master/distributed/executor.py#L142
because there is not `daemon` argument to `Thread` in that version of python.

The backward compatible way to control this is to modify the `daemon` property of the Thread object after it is created, but before `start()` is called:
https://docs.python.org/2/library/threading.html#threading.Thread.daemon

**Comment by mrocklin** [comment]
Fixed.  More generally the problem here is that we're not actively testing Python 2.7.  

There are odd issues that pop up there on the travis.ci machines that I should resolve to get that into the testing matrix.

**Comment by mrocklin** [comment]
@seibert let me know if I should push a release with this change.

**Comment by seibert** [comment]
I'm currently testing with 1.3.0, so I don't think it is critical. (I created a new environment that grabbed 1.3.2 by default, which is how I found this issue.)

**Comment by mrocklin** [comment]
Verified that py27 passes tests locally (though it still fails on travis.ci.)  Have pushed and released 1.3.3
