### ISSUE TITLE
Setting resource locality when calling Executor.submit

### ISSUE THREAD

**Issue by seibert** [mrocklin/distributed#5]
I can think of a few use cases where certain tasks need to be executed on particular nodes:
 * Partitioning of input files onto different nodes of a cluster (possibly with some redundancy) means that initial file read tasks must run on a subset of the workers.
 * Heterogeneous clusters where some tasks can run on low memory systems, but a few tasks need to run on a high memory system.
 * Similar to above, but some nodes have GPUs and others do not.

One possible API for this could look like:
```python
executor = Executor(('127.0.0.1', 8787)) 
a = executor.submit(add, 1, 2, _allowed_workers=['192.168.1.100:8787', '192.168.1.101:8787']) 
```
The `_allowed_workers` kwarg is has a leading underscore to attempt to avoid collision with any kwargs of the user function being submitted.

As a related feature, it would be nice if workers could register themselves with unique identifiers that could be used with `_allowed_workers` instead of the full IP address and port.

**Comment by mrocklin** [comment]
What are your thoughts on handling this by restricting data rather than restricting computations.

E.g.

```python
>>> a = send('192.168.1.100:8787', 1)
>>> b = send('192.168.1.102:8787', 2)
>>> type(a)
RemoteData

>>> c = executor.submit(add, a, b)
```

**Comment by seibert** [comment]
So in the case of my file example, I would send the filename to only the workers that have it?  Is there a way to indicate that the data is replicated on 2 or 3 workers?

Restricting the data wouldn't handle the situation where special computing resources are required, but that use case is more theoretical.  (I've had fewer situations in the past where that would have been helpful.)

**Comment by mrocklin** [comment]
Yeah, we'd probably do something like the following:

```python
scatter({'filename.1.txt': ['192.168.1.100:8787', '192.168.2.100:8787'],
         'filename.2.txt': ['192.168.2.100:8787', '192.168.3.100:8787'],
         'filename.3.txt': ['192.168.3.100:8787', '192.168.4.100:8787']}, type='all')
```

Putting data explicitly in place jives much more strongly with the existing scheduler system and is a fairly trivial operation.  Not to say that we couldn't also add computation locality constraints.  They're both quite doable.

**Comment by seibert** [comment]
OK, that seems like a reasonable approach.
