### ISSUE TITLE
Tune update_state

### ISSUE THREAD

**Issue by mrocklin** [mrocklin/distributed#6]
The `Executor.submit` function can be used *many times* within for loops while building up a complex computation.  This can be a powerful way to write down strange computations with a simple API.  If possible we'd like to make this fast, even for large numbers of submit calls.  Unfortunately this is currently somewhat costly, limiting our ability to build up computations directly in this way.

I suspect that most of the cost is in `distributed/scheduler.py:update_state` which is run after any `submit`, `map`, or `get` call.  The `update_state` function updates the scheduler's runtime state with a new graph.  In the case of `submit` this new graph is very small (just one key-value pair) but the function is often called many times.  At the moment this function depends somewhat on the size of the current internal graph, and not just on the new graph being added.  This can cause significant slowdowns when using submit repeatedly on already large internal graphs.

### Some solutions

1.  Don't use `submit` willy-nilly, and instead ask the user to build up the graphs externally with a tool like `dask.do` and submit those in larger chunks instead.
2.  Batch many submit calls into larger graphs internally on the scheduler side.  This can probably help to keep down `update_state` overhead
3.  Tune `update_state` so that it is linear in the size of the input graph, and somewhat speedy.

If possible I'd like to make `update_state` fast.  It will probably be important if we have long-running schedulers in the future with large internal graphs.  We might as well push a bit on this early so that we can rely on it later.

### Small benchmark script

```python
from distributed.scheduler import update_state
from operator import add
from time import time

def bench_update_state(n):
    dsk = {}
    dependencies = {}
    dependents = {}

    waiting = {}
    waiting_data = {}

    held_data = set()
    in_memory = set()
    processing = set()
    released = set()

    update_state(dsk, dependencies, dependents, held_data,
                 in_memory, processing, released,
                 waiting, waiting_data, {('y', 0): 0}, {('y', 0)})

    for i in range(n):
        new_dsk = {('x', i): i, ('y', i): (add, ('y', i - 1), ('x', i))}
        new_keys = {('y', i)}
        update_state(dsk, dependencies, dependents, held_data,
                     in_memory, processing, released,
                     waiting, waiting_data, new_dsk, new_keys)

if __name__ == '__main__':
    import sys
    n = int(sys.argv[1])
    start = time()
    bench_update_state(n)
    end = time()
    print("%4f seconds" % (end - start))
```

### Non-linear costs

By running this script at higher values of n we see non-linear costs:

```
mrocklin@notebook:~/workspace/distributed$ python bench_update_state.py 10
0.001004 seconds
mrocklin@notebook:~/workspace/distributed$ python bench_update_state.py 100
0.011575 seconds
mrocklin@notebook:~/workspace/distributed$ python bench_update_state.py 1000
0.155894 seconds
mrocklin@notebook:~/workspace/distributed$ python bench_update_state.py 10000
15.132474 seconds
```

### Most of the cost in the `update_state` function itself

If you run this with the profiler

    $ python -m cProfile -o p.out bench_update_state.py  10000
    $ pip install snakeviz
    $ snakeviz p.out

You'll find that about 2.7 seconds is spent within `keys_outside_frontier` and the rest of the time is spent within the `update_state` function itself.

cc @eriknw, in case he wants to resurrect his tuning skills and dive into the scheduler's guts.

**Comment by mrocklin** [comment]
Hrm, looks like most of the time is spent here

    frontier = in_memory | set(waiting) | processing

I'll spend a bit more time on this myself in the immediate future.

**Comment by mrocklin** [comment]
This is mostly fixed.  As seems to be a common theme, the solution to speed up schedulers seems to be "add more state."  I've had to maintain a new variable `in_play` that includes all of the keys that are either are or will eventually be in-memory.  

Timings

```
mrocklin@notebook:~/workspace/distributed$ python bench_update_state.py 1000
0.088687 seconds
mrocklin@notebook:~/workspace/distributed$ python bench_update_state.py 10000
0.935115 seconds
mrocklin@notebook:~/workspace/distributed$ python bench_update_state.py 100000
10.320588 seconds
mrocklin@notebook:~/workspace/distributed$ python bench_update_state.py 1000000
189.866686 seconds
```

We see about a `100us` cost per task that very slowly rises.  Still doesn't seem to be entirely linear but it's pretty close.

**Comment by eriknw** [comment]
Just got this ping.  Hurray for profiling and benchmarking!  This makes me think I should add snakeviz support and Jupyter integration to `benchtoolz`.
> As seems to be a common theme, the solution to speed up schedulers seems to be "add more state.

Seconded!
